---
- name: getting ip address
  ec2_remote_facts:
     aws_access_key: "{{aws_access_key}}"
     aws_secret_key: "{{aws_secret_key}}"
     region: "{{region}}"
     filters:
        "tag:Name": CICDAppServer1
  register: ec2_facts
- name: Add the virtual host configuration in httpd.conf
  blockinfile:
   path: /etc/httpd/conf/httpd.conf
   mode: 0664
   block: |
      <VirtualHost *:80>
      ProxyPass / http://{{ec2_facts.instances[0].private_ip_address}}:8080/
      ProxyPassReverse / http://{{ec2_facts.instances[0].private_ip_address}}:8080/
      </VirtualHost>
- name: print output
  debug: 
   var: ec2_facts.instances[0].private_ip_address
- name: Copy index.html file
  copy: src=files/index.html dest=/var/www/html
  notify:
  - restart apache
